<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bus_seat;
use DB;
use Illuminate\Database\Factory\SeatFactory;

class SeatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // This seeder does not work
        $seatCounts = 5;

        for($i=1; $i<=$seatCounts; $i++) {
            if ($i == 3 && $i == 1) {
                continue;
            } 
            Seat::factory()->create([
                'seat_number' => 'G'.$i,
                'seat_type' => $i % 2 == 0 ? 'Aisle' : 'Window'
            ]);
        }

        /*
            SQL
            INSERT INTO `tbl_bus_seat` (`id`, `bus_id`, `seat_number`, `seat_type`, `storage_id`, `price_id`, `status`, `created_at`, `updated_at`) VALUES 
            (NULL, '6', 'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'A2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '6', 'A4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'A5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'B4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'B5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'C1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'C2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '6', 'C4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'C5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'D1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'D2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'D4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'D5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'E1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'E2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '6', 'E4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'E5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'F1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'F2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'F4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'F5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '6', 'G1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'G2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '6', 'G4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'G5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'H1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'H2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'H4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'H5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '6', 'I1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'I2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'I3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'I4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '6', 'I5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'A2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'A4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'A5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'B4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'B5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'C1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'C2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'C4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'C5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'D1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'D2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'D4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'D5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'E1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'E2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'E4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'E5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'F1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'F2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'F4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'F5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'G1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'G2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'G4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'G5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'H1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'H2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'H4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'H5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '7',  'I1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'I2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'I3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'I4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '7',  'I5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'A2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'A4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'A5', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'B4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'B5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'C1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'C2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'C4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'C5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'D1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'D2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'D4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'D5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'E1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'E2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'E4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'E5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'F1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'F2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'F4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'F5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'G1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'G2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'G4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'G5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'H1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'H2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'H4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'H5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '8',  'I1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'I2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'I3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'I4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '8',  'I5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'A2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'A4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'A5', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'B4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'B5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'C1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'C2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'C4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'C5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'D1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'D2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'D4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'D5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'E1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'E2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'E4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'E5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'F1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'F2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'F4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'F5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'G1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'G2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'G4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'G5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'H1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'H2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'H4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'H5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '9',  'I1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'I2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'I3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'I4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '9',  'I5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'A2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'A4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'A5', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'B4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'B5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'C1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'C2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'C4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'C5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'D1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'D2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'D4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'D5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'E1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'E2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'E4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'E5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'F1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'F2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'F4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'F5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'G1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'G2', 'Aisle', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'G4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'G5', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'H1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'H2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'H4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'H5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '10',  'I1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'I2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'I3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'I4', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '10',  'I5', 'Window', '1', '1', 'Available', NULL, NULL),
            (NULL, '11',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '11',  'A2', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '11',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '11',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '11',  'B3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '11',  'B4', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'A2', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'B3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'B4', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '13',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '13',  'A2', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '13',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '13',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '13',  'B3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '13',  'B4', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '12',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '14',  'A2', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '14',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '14',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '14',  'B3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '14',  'B4', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '15',  'A1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '15',  'A2', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '15',  'B1', 'Window', '1', '1', 'Available', NULL, NULL), 
            (NULL, '15',  'B2', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '15',  'B3', 'Aisle', '1', '1', 'Available', NULL, NULL), 
            (NULL, '15',  'B4', 'Window', '1', '1', 'Available', NULL, NULL);
        */

    }
}
